### ISSUE TITLE
Новый ЕН

### ISSUE THREAD

**Issue by pehser** [lis-dev/nova-poshta-api-2#1]
Не нашол фукцию создаюшюю ЕН может я не разобрался но доки нет

**Comment by Hukuta** [comment]
Уже пофиксили 

> Но всё не так плохо: на данный момент можно в качестве отправителя указывать контрагента, созданного с параметром CounterpartyProperty = Recipient. Скорее всего это баг и его исправят, но пока что это наиболее приемлемый способ для создания нового контрагента чтобы сформировать
