### ISSUE TITLE
Яким чином можна вказати розміри вантажу під час розрахунку вартості доставки?

### ISSUE THREAD

**Issue by Matvik** [lis-dev/nova-poshta-api-2#12]
Вартість доставки залежить від габаритів. але функція не має таких параметрів. відповідно, на більших габаритах вартість доставки невірна

**Comment by lis-dev** [comment]
Думаю, Вам необходимо попробовать указать в поле "вес" то, что в документации называют "объёмный вес"

Цитата из доки https://my.novaposhta.ua/data/API2-200215-1622-28.pdf

> Объемный вес – учитывается при оформлении объемных и относительно легких отправлений. Определяется путем
> использования формул:
> Объемный вес(кг)=Длинна(см)хШирина(см)хВысота(см)/4000 или
> Объемный вес(м
> )=Объемх250

**Comment by Matvik** [comment]
Дякую, вже розібрався. викликаю просто загальним методом для виклику метода
`$response = $this->_np
                ->model('InternetDocument')
                ->method('getDocumentPrice')
                ->params(array(
                    'CitySender' => $senderCityRef,
                    'CityRecipient' => $recCityRef,
                    'ServiceType' => 'WarehouseWarehouse',
                    'Cost' => $price,
                    'OptionsSeat' => [
                        [ 
                            'volumetricWidth' => $width,
                            'volumetricLength' => $length,
                            'volumetricHeight' => $height,
                            'Weight' => $weight
                         ]
                     ]
                 ))
                ->execute();`
В масиві  'OptionsSeat' можна вказувати параметри для кожного місця вантажа.
