### ISSUE TITLE
getDocumentList

### ISSUE THREAD

**Issue by pehser** [lis-dev/nova-poshta-api-2#24]
Покажите как правильно пользоваться getDocumentList? у меня постоянно возрощяет пусто :(

```
$np = new NovaPoshtaApi2(NPKEY, 'ru');
$rez=$np->getDocumentList(array('GetFullList'=>1, "DateTimeFrom"=>"01.10.2018", "DateTimeFrom" => "12.10.2018"));
print_r($rez);
```

> Array
> (
>     [success] => 1
>     [data] => Array
>         (
>         )
>     [errors] => Array
>         (
>         )
>     [warnings] => Array
>         (
>         )
>     [info] => Array
>         (
>             [totalCount] => 0
>         )
>     [messageCodes] => Array
>         (
>         )
>     [errorCodes] => Array
>         (
>         )
>     [warningCodes] => Array
>         (
>         )
>     [infoCodes] => Array
>         (
>         )
> 
> )

**Comment by mygeweb** [comment]
У меня тоже самое. С разными датами возмращает success => 1 но при этом пустой массив в data

**Comment by lis-dev** [comment]
- Проверьте соответствие ключа АПИ аккаунту, в котором созданы накладные.
- Проверьте, не истёк ли срок действия ключа.
- Проставьте дату DateTimeFrom равной текущей-1 день и DateTimeTo+1 день (есть вероятность, что сервера Новой Почты находятся не в Украине и работают в другом часовом поясе).
- Просмотрите созданные накладные, когда у них выставлена дата отправки (поле DateTime). Если накладная создана, например, на послезавтра, то она не будет отображаться, если выбрана только сегодняшняя дата в параметрах DateTimeFrom и DateTimeTo
