### ISSUE TITLE
Не хочет подключать класс

### ISSUE THREAD

**Issue by kolomat** [lis-dev/nova-poshta-api-2#30]
Fatal error: Class 'NovaPoshtaApi2' not found in F:\OSPanel\domains\test.loc\nova.php on line 3
После установки выдает такую ошибку. В чем может быть проблема?

**Comment by lis-dev** [comment]
Необходимо подключить файлы классов или с помощью composer, или напрямую (например, с помощью include)

**Comment by yapizza** [comment]
Тоже самое, класс по инструкции не подключается

**Comment by sim2github** [comment]
Работают оба способа.
```php
<?php
// ПОДКЛЮЧЕНИЕ
// Первый способ через composer
// require __DIR__ . '/vendor/autoload.php';

// Второй способ через release архив и require
require __DIR__ . '/nova-poshta-api-2-master/src/Delivery/NovaPoshtaApi2.php';

$np = new \LisDev\Delivery\NovaPoshtaApi2('Ваш_ключ_API_2.0');
var_dump($np);
```

**Comment by sim2github** [comment]
Видимо Вы указали неправильный `namespace` 
```php
object(LisDev\Delivery\NovaPoshtaApi2)#1 (9) { ["key":protected]=> string(23) "Ваш_ключ_API_2.0" ["throwErrors":protected]=> bool(false) ["format":protected]=> string(5) "array" ["language":protected]=> string(2) "ru" ["connectionType":protected]=> string(4) "curl" ["areas":protected]=> NULL ["model":protected]=> string(6) "Common" ["method":protected]=> NULL ["params":protected]=> NULL }
```

**Comment by yapizza** [comment]
> Работают оба способа.
> 
> ```
> <?php
> // ПОДКЛЮЧЕНИЕ
> // Первый способ через composer
> // require __DIR__ . '/vendor/autoload.php';
> 
> // Второй способ через release архив и require
> require __DIR__ . '/nova-poshta-api-2-master/src/Delivery/NovaPoshtaApi2.php';
> 
> $np = new \LisDev\Delivery\NovaPoshtaApi2('Ваш_ключ_API_2.0');
> var_dump($np);
> ```

Спасибо, так работает. В инструкции не указано $np = new \LisDev\Delivery\NovaPoshtaApi2('Ваш_ключ_API_2.0');

**Comment by sim2github** [comment]
В инструкции опущена шапка с подключением библиотеки:
```php
<?php 
require __DIR__ . '/vendor/autoload.php';
use LisDev\Delivery\NovaPoshtaApi2;

// Далее по инструкции
$np = new NovaPoshtaApi2('Ваш_ключ_API_2.0');
```

**Comment by lis-dev** [comment]
@sim2github , спасибо, добавил ясности в README
