### ISSUE TITLE
getCounterparties

### ISSUE THREAD

**Issue by ivankorobchukrabbi** [lis-dev/nova-poshta-api-2#32]
Не могу понять, при вызове $senderInfo = $this->np->getCounterparties('Sender', 1, '', '');
в ответ приходит

> [
  "success" => true
  "data" => array:1 [
    0 => array:13 [
      "Description" => "Приватна особа"
      "Ref" => "dadb580b-7c5c-11e8-8b24-00"
      "City" => "00000000-0000-0000-0000-0000"
      "Counterparty" => null
      "FirstName" => "Приватна особа"
      "LastName" => ""
      "MiddleName" => ""
      "CounterpartyFullName" => ""
      "OwnershipFormRef" => ""
      "OwnershipFormDescription" => ""
      "EDRPOU" => ""
      "CounterpartyType" => "PrivatePerson"
      "CityDescription" => ""
    ]
  ]
  "errors" => []
  "warnings" => []
  "info" => array:1 [
    "totalCount" => 1
  ]
  "messageCodes" => []
  "errorCodes" => []
  "warningCodes" => []
  "infoCodes" => []
]

Нету даных отправителя. В чем ошибка?

**Comment by lis-dev** [comment]
А какие данные введены в личном кабинете пользователя?

Более подробную информацию об отдаваемом результате можно посмотреть на странице документации: https://devcenter.novaposhta.ua/docs/services/557eb8c8a0fe4f02fc455b2d/operations/557fd789a0fe4f105c08760f

**Comment by ivankorobchukrabbi** [comment]
Спасибо, я понял. Еще один вопрос. Когда создаешь накладную ругается на то что ему не хватает 'ContactRecipient' и  'Recipient'. Сам вопрос как эти поля получить?

**Comment by quarts-zzz** [comment]
При использовании $np->getCounterparties('Sender', 1, '', ''); город пустой - [City] => 00000000-0000-0000-0000-000000000000

В личном кабинете так и не понял где указать город. В новом кабинете http://new.novaposhta.ua добавил адрес отправителя. Как его получить в API?

**Comment by Craft-Lawrence** [comment]
> Спасибо, я понял. Еще один вопрос. Когда создаешь накладную ругается на то что ему не хватает 'ContactRecipient' и 'Recipient'. Сам вопрос как эти поля получить?

А я не понял) Объясните пожалуйста. 
У меня в личном кабинете заполнен адрес, но тоже City выдаёт кучу нулей.

**Comment by lis-dev** [comment]
> > Спасибо, я понял. Еще один вопрос. Когда создаешь накладную ругается на то что ему не хватает 'ContactRecipient' и 'Recipient'. Сам вопрос как эти поля получить?
> 
> А я не понял) Объясните пожалуйста.
> У меня в личном кабинете заполнен адрес, но тоже City выдаёт кучу нулей.



Здесь неверно отрабатывает API Новой Почты. Попробуйте использовать этот код для получения адресов отправителей:
`   $np = new NovaPoshtaApi2('6957370040472142991682e2cea51a3a');
    $addresses = $np
        ->model('AddressContactPersonGeneral')
        ->method('getAddresses')
        ->params(['ContactPersonRef' => "527c5ea6-16b6-11e9-8b24-005056881c6b"])
        ->execute();`

**Comment by Craft-Lawrence** [comment]
> > > Спасибо, я понял. Еще один вопрос. Когда создаешь накладную ругается на то что ему не хватает 'ContactRecipient' и 'Recipient'. Сам вопрос как эти поля получить?
> > 
> > 
> > А я не понял) Объясните пожалуйста.
> > У меня в личном кабинете заполнен адрес, но тоже City выдаёт кучу нулей.
> 
> Здесь неверно отрабатывает API Новой Почты. Попробуйте использовать этот код для получения адресов отправителей:
> 
> ```
>     $np = new NovaPoshtaApi2('....');
>     $addresses = $np
>         ->model('AddressContactPersonGeneral')
>         ->method('getAddresses')
>         ->params(['ContactPersonRef' => "...."])
>         ->execute();
> ```

Спасибо, помогло. Правда пришлось в документации Новой почты через её "Try it" вытянуть недостающие данные. Но всё заработало.
