### ISSUE TITLE
Error: Class 'LisDev\Delivery\NovaPoshtaApi2' not found in .....DeliveryForm.php:76

### ISSUE THREAD

**Issue by luckyalexandr** [lis-dev/nova-poshta-api-2#33]
Прежде всего спасибо за расширение. Очень удобное и понятное, но...
На днях ни с того ни с сего стал получать `Error: Class 'LisDev\Delivery\NovaPoshtaApi2' not found in ....../DeliveryForm.php:76`
Но все в данном файле на месте и самым первым юзом стоит `use LisDev\Delivery\NovaPoshtaApi2`.
Как это понять и куда копать - ума не приложу...

**Comment by lis-dev** [comment]
Добрый день. Сначала проверьте, что файл с классом LisDev\Delivery\NovaPoshtaApi2 действительно существует. Во-вторых проверьте, что в он подключен (т.е. в вашем коде должен присутствовать include('путь_к_файлу_NovaPoshtaApi2.php')

**Comment by luckyalexandr** [comment]
Кроме use должен быть еще и include?

**Comment by luckyalexandr** [comment]
Помогло удалить директорию vendor и переустановка...
Только теперь пропал список областей, как минимум ((
Прям магия какая-то.
Но, поидее области я сейчас найду.

**Comment by lis-dev** [comment]
Области берутся из файла NovaPoshtaApi2Areas.php
