### ISSUE TITLE
Данная библиотека поддерживается ? 

### ISSUE THREAD

**Issue by nepster-web** [lis-dev/nova-poshta-api-2#34]
Собственно сабж

**Comment by lis-dev** [comment]
Библиотека работает, иногда происходят улучшения. Чем вызван вопрос?

**Comment by nepster-web** [comment]
В некоторых местах необъявленая переменная https://github.com/lis-dev/nova-poshta-api-2/blob/master/src/Delivery/NovaPoshtaApi2.php#L427

В случае успешного ответа (когда ошибок нет) на последних версиях пхп вылетает эксепшин. 
Увидел менрдж с 2019 года 

https://github.com/lis-dev/nova-poshta-api-2/pull/29

**Comment by lis-dev** [comment]
Решение реализовано здесь:
https://github.com/lis-dev/nova-poshta-api-2/blob/master/src/Delivery/NovaPoshtaApi2.php#L412

Спасибо
