### ISSUE TITLE
Ошибка в коде .. Данный код не работает

### ISSUE THREAD

**Issue by Mausina** [lis-dev/nova-poshta-api-2#39]
// В параметрах указывается город и область (для более точного поиска)
$city = $np->getCity('Киев', 'Киевская');
$result = $np->getWarehouses($city);

**Comment by lis-dev** [comment]
В методе getWarehouses используйте в качестве первого параметра id города, а не весь массив данных, полученных в результате getCity. 

Следующий код вернёт всю информацию по складам в Киеве:

```
$city = $np->getCity('Киев', 'Киевская');
$result = $np->getWarehouses($city['data'][0]['Ref']);
```

**Comment by lis-dev** [comment]
README исправлен:
https://github.com/lis-dev/nova-poshta-api-2/commit/af8a76c05b141f14278f20e29b695b3154c812b7

**Comment by Mausina** [comment]
Та как исправить я знал .. просто помогаю с развитием библы
