### ISSUE TITLE
Создаются не в тот город

### ISSUE THREAD

**Issue by RemizovAnton** [lis-dev/nova-poshta-api-2#41]
Добрый день, подключил библиотеку, все работает , спасибо, но столкнулся уже второй раз с проблемой, что создало ттн не в тот город. кидаю код: 

array(
            'FirstName' => $row_order_data['order_name'],
            'MiddleName' => $row_order_data['order_patronymic'],
            'LastName' => $row_order_data['order_surname'],
            'Phone' => $row_order_data['order_phone'],
            'City' => 'Калинівка',
            'Region' => 'Київська',
            'Warehouse' => 'Відділення №1: вул. Центральна, 57',
        ),

Если данные получателя будут по такому адресу и городу- то к сожалению ттн создается на такое отделение :

Калинівка (Броварський р-н), Відділення № 1: вул. Чернігівська, 9/1

Было еще одно село, что так создалось..

Кто то сталкивался с такой проблемой?

**Comment by RemizovAnton** [comment]
Вот еще такая же ф..ня

Кам'янське Дніпропетровська обл Відділення №1: бул. Незалежності, 2а - нужно сюда создать, а создается на 

Кам'янське (Нікопольський р-н), Пункт приймання-видачі (до 30 кг): вул. Будівників, 3а 

😡😡😡 Что, никто не сталкивался с такой проблемой?

**Comment by lis-dev** [comment]
Спасибо за информацию, уже исследую данную проблему. О результатах отпишу.

**Comment by lis-dev** [comment]
Для городов, которых по стране более 1 имеет смысл указывать название полностью вместе с районом. 
Полные названия населенных пунктов можно увидеть с помощью запроса `$np->getCities(0, 'Калиновка');` : по стране их 9, по области - 3).  

Для быстрого фикса рекомендую заменить
`'City' => 'Калинівка'` на `'City' => 'Калинівка(Васильківський р-н.)',`  и
`'City' => "Кам'янське" ` на 'City' => "Кам'янське(Дніпропетровська обл)" соответственно. 

В дальнейших версиях библиотеки такие города будут учтены и адрес склада так же будет приниматься во внимание при определении города по его названию.

**Comment by lis-dev** [comment]
Fixed: https://github.com/lis-dev/nova-poshta-api-2/releases/tag/0.1.4
