### ISSUE TITLE
Создаются не в тот город 2

### ISSUE THREAD

**Issue by RemizovAnton** [lis-dev/nova-poshta-api-2#43]
Доброй ночи, с теми городами что я писал в вопросе 41 проблема решилась, спасибо Вам, но...(

теперь если город получателя будет - м. Покровськ, Покровська міськрада, Донецька обл. и выбрать отделение например - Відділення №2 (до 30 кг на одне місце): мкрн. Шахтарський, ТЦ
то создается накладная вот сюда :
Покровське (Мангушський р-н), Відділення №1: вул. Азовської флотилії, 2 (пос. Моряків)

**Comment by lis-dev** [comment]
Fixed2: https://github.com/lis-dev/nova-poshta-api-2/releases/tag/0.1.5
