### ISSUE TITLE
Неоголошена змінна $error

### ISSUE THREAD

**Issue by VladBo** [lis-dev/nova-poshta-api-2#5]
Якшо немає errors, то вилітає notice, що $error не оголошена в методах getCity, getWarehouse, getArea.

Наприклад:

Notice: Undefined variable: error in src/Delivery/NovaPoshtaApi2.php on line 448

Fix:
оголосити змінну 
$error = NULL;

**Comment by fomvasss** [comment]
Чуму досі не виправили помилку чи не прийняли pull-request?!

**Comment by lis-dev** [comment]
Решение реализовано здесь:
https://github.com/lis-dev/nova-poshta-api-2/blob/master/src/Delivery/NovaPoshtaApi2.php#L412

Спасибо
