### ISSUE TITLE
Наложенный платёж с отправкой денег на карту

### ISSUE THREAD

**Issue by Craft-Lawrence** [lis-dev/nova-poshta-api-2#52]
Такое вообще возможно организовать? Не нашёл инфы ни в документации, ни в данной либе. Может через подписание каких-то договоров?
Написал в техподдержку - молчат второй день.
Без возможности автоматически создавать накладные  90% функциональности всего API отмирает.

**Comment by lis-dev** [comment]
Думаю, вам нужно это:
https://devcenter.novaposhta.ua/docs/services/556eef34a0fe4f02049c664e/operations/575fe852a0fe4f0aa0754760/console пункт 2) Формирование запроса с заказом услуги «Обратная доставка денег» . Параметр `BackwardDeliveryData`  c типом `"CargoType": "Money"` . 
На счёт куда эти деньги придут (на карту или нужно их забирать) - информации нет. Если Новая  Почта даст вам ответ - отпишите, пожалуйста, здесь.

**Comment by KitDevUA** [comment]
> Если Новая Почта даст вам ответ - отпишите, пожалуйста, здесь.

Дала, и не утешительный. Сказали, что направлять оплату на карту через API нельзя и в будущем не предвидится.
Такая мера безопасности.
Но при этом я почти наверняка знаю, что один крупнейший магазин осуществляет закупки через Новую почту и оплата идёт автоматом на карту. Есть какой-то закрытый клуб)

**Comment by pinchukd** [comment]
При чем тут АПИ. Для возврата денег на карту - вам нужно заключить договор. А то, где вы делаете накладные - ваше дело. АПИ или вручную...

**Comment by pinchukd** [comment]
Или там есть особая опция для возврата именно на карту договора?

**Comment by KitDevUA** [comment]
> При чем тут АПИ. Для возврата денег на карту - вам нужно заключить договор. А то, где вы делаете накладные - ваше дело. АПИ или вручную...

Не совсем понял, о каком именно возврате денег речь. Лично я имел в виду наложенный платёж. В этом плане мне дали понять, что никакой договор не даст мне такой возможности т.к. в API Новой почты нет возможности направить деньги на карту. Только на отделение.

Но я после создания накладных раз в день-два вручную через бизнес-кабинет это меняю.
