### ISSUE TITLE
Невозможно установить VolumeGeneral = 0.51

### ISSUE THREAD

**Issue by Craft-Lawrence** [lis-dev/nova-poshta-api-2#53]
Как бы я ни указывал нужную мне величину, до API доходит 0.5. Пробовал передавать как числом, так и строкой.

**Comment by lis-dev** [comment]
Код
```
    $np = new NovaPoshtaApi2('...', 'ru', true, 'file_get_contents');
    $existingSender = $np->getCounterparties('Sender', 1, '', '');
    $sender = $existingSender['data'][0];
    $documentData = $np->newInternetDocument(
        [
            'LastName' => $sender['LastName'],
            'FirstName' => $sender['FirstName'],
            'MiddleName' => $sender['MiddleName'],
            'City' => 'Киев',
            'Region' => 'Киевская',
            'Warehouse' => 'Отделение №1: ул. Пироговский путь, 135',
        ],
        [
            'FirstName' => 'Сидор',
            'MiddleName' => 'Сидорович',
            'LastName' => 'Сиродов',
            'Phone' => '0509998877',
            'City' => 'Киев',
            'Region' => 'Киевская',
            'Warehouse' => 'Отделение №3: ул. Калачевская, 13 (Старая Дарница)',
        ],
        [
            'DateTime' => date('d.m.Y', time() + 4 * 84600),
            'ServiceType' => 'WarehouseWarehouse',
            'PaymentMethod' => 'Cash',
            'PayerType' => 'Recipient',
            'Cost' => '500',
            'SeatsAmount' => '1',
            'Description' => 'Спутник',
            'CargoType' => 'Cargo',
            'Weight' => '10',
            'VolumeGeneral' => '0.51', // <--------- 0.51
        ]
    );
    $result = $np->getDocument($documentData['data'][0]['Ref']);
    var_dump($result['data'][0]['VolumeGeneral']);
```

Возвращает 
```
string(4) "0.51"
```

**Comment by KitDevUA** [comment]
> Код
> .....
> Возвращает
> 
> ```
> string(4) "0.51"
> ```

Тысяча извинений, но я не понял)
Я пробовал указывать и как интовое, и как стринговое.

p.s. Но я решил вопрос на Новой почте. Оказывается, если для коробки 17х12х10 (которая по расчётам даёт 0.51 и стоимость отправки 45грн+) указать объём 0.5 (где стоимость отправки уже 40грн), их это не особо беспокоит :)

**Comment by lis-dev** [comment]
Код приведенный выше показывает, что библиотека отправляет в API VolumeGeneral именно то значение, которое указано в параметре VolumeGeneral. Вероятно, есть проблема расчёта значения VolumeGeneral  в коде вашего приложения.

**Comment by KitDevUA** [comment]
> Код приведенный выше показывает, что библиотека отправляет в API VolumeGeneral именно то значение, которое указано в параметре VolumeGeneral. Вероятно, есть проблема расчёта значения VolumeGeneral в коде вашего приложения.

Я ничего не рассчитываю, а просто вручную прописываю значение т.к. товар всегда один и тот же. Написал об этом в их саппорт, но уже дня 3 тишина.
