### ISSUE TITLE
getAreas

### ISSUE THREAD

**Issue by anydasa** [lis-dev/nova-poshta-api-2#6]
Данный метод есть у новой почты. "getAreas"

**Comment by anydasa** [comment]
я бы выросил curl. и использовал file_get_contents

$result = file_get_contents($url, null, stream_context_create(array(
            'http' => array(
                'method'           => 'POST',
                'header'           => "Content-type: application/x-www-form-urlencoded;\r\n",
                'content'          => $post,
            ),
        )));

**Comment by lis-dev** [comment]
anydasa, 
Действительно, недавно НоваяПочта обновила API и добавила несколько методов, которые будут реализованы в классе в ближайшее время.
Спасибо, что следите за обновлениями

**Comment by lis-dev** [comment]
К сожалению, getAreas в данный момент возвращает название области только на украинском языке, что делает её практически бесполезной при определении города по его названию и области, введенными по-русски. Поэтому, на данный момент, не вижу большого смысла вносить изменения в код. В дальнейшем же, когда появятся русские названия, костыль с областями будет убран.

**Comment by lis-dev** [comment]
Что же касается использования file_get_contents вместо curl, не могли бы Вы аргументировать Ваш выбор?

**Comment by anydasa** [comment]
Curl менее понятный, и требует отдельную библиотеку. Я например его в своих проектах не использую, потому пришлось подключать. Это конечно все ИМХО. Кстати getAreas я не смог получить Вашей либой из коробки. После замены на file_get_contents все получилось. Я не анализировал, причину не знаю. Может и не в этом проблемма была.

**Comment by anydasa** [comment]
Что до getAreas нет русского, так там у них много такого:) например отделения Киева, не везде есть русский перевод. Лично я заливаю данные себе к базу, и оттуда уже использую. И на своей стороне уже слежу за целостностью данных. А вообще у Новой Почты всяких недоделок много, например есть склады у которых нет города.

**Comment by lis-dev** [comment]
Действительно, необходимость в установке отдельной библиотеки при использовании curl - весомый аргумент в пользу file_get_contents. Я добавил возможность использовать для запросов как curl (по умолчанию), так и file_get_contents. Спасибо за наводку!
Будем надеяться, что и в Новой Почте тоже на месте не стоят и фиксят баги :)

**Comment by Dsqwared** [comment]
lis-dev, не силен в ООП, хочу на винде, внедрить в Wordpress ваш класс уже неделю мучаюсь, не получается.... 
что делал, 
1 скачал архив https://github.com/lis-dev/nova-poshta-api-2/archive/master.zip
2 распаковал (получилось две папки src и tests) и composer.json не знаю для чего он :(
3. include_once('class/tests/NovaPoshtaApi2Test.php')
получаю ошибку -  Class 'PHPUnit_Framework_TestCase' not found in ***

может есть возможность связаться по skype ?

**Comment by Dsqwared** [comment]
Добрый день
подключил класс
при вызове пишет Class 'NovaPoshtaApi2' not found in  

что может быть?

**Comment by Dsqwared** [comment]
Добрый день
подключил класс
при вызове пишет Class 'NovaPoshtaApi2' not found in  

что может быть?

взрыв мозга.... два часа потратил на решение...
оказалось...

класс не находился никак пока я не создал новый файл, кинул туда весь текст "без шапки" (с шапкой даже так не работало)
подключил уже этот файл...
и только так заработало...  не знаю что это.... было...

**Comment by anydasa** [comment]
вы не тот файл подключаете)) вам нужен \src\Delivery\NovaPoshtaApi2.php

23 июня 2015 г., 15:49 пользователь Dsqwared <notifications@github.com>
написал:

> Добрый день
> подключил класс
> при вызове пишет Class 'NovaPoshtaApi2' not found in
>
> что может быть?
>
> взрыв мозга.... два часа потратил на решение...
> оказалось...
>
> класс не находился никак пока я не создал новый файл, кинул туда весь
> текст "без шапки" (с шапкой даже так не работало)
> подключил уже этот файл...
> и только так заработало... не знаю что это.... было...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lis-dev/nova-poshta-api-2/issues/6#issuecomment-114484250>
> .
>



-- 
Атмарама дас

**Comment by Dsqwared** [comment]
я его и подключал... просто я уже эксперементировал и в конце концов кинул его в одну директорию с файлом из которого подключал класс

**Comment by awanport** [comment]
Дайте пожалуйста пример как вывести данные.
<?
$page = file_get_contents ( 'novaposhtaapi2.php' );
$np = new NovaPoshtaApi2 ('3776667766556еннн7755');
$recipient_city = $np->getCity('Киев', 'Киевская');
$recipient_city_ref = $recipient_city['data'][0]['Ref'];
var_export($result);
?>
белый экран

**Comment by Dsqwared** [comment]
$np = new NovaPoshtaApi2('ВАШ КЛЮЧ');
$city = $np->getCity('Киев');
$result = $np->getWarehouses($city['data'][$i]["Ref"]);
var_dump($result);

**Comment by awanport** [comment]
Уже второй день мучаюсь! дайте пожалуйста исправленные файлы с примером. 
С интаймом получилась только кода исправил ошибки указанные здесь. https://github.com/lis-dev/intime-api-2/pull/1

**Comment by Dsqwared** [comment]
попробуй убрать шапку 

namespace LisDev\Delivery;
/**
 * Nova Poshta API Class
 * 
 * @author lis-dev
 * @see https://my.novaposhta.ua/data/API2-200215-1622-28.pdf
 * @see https://github.com/lis-dev
 * @license MIT
 */

мне помогло

**Comment by awanport** [comment]
убирал не помогает

**Comment by Dsqwared** [comment]
убедись что класс подключается... я еще с этим парился... пока файл рядом не положил не получалось подключить... 

смешно или не смешно... 

но еще... пока не создал новый файл, и не скопировал туда текст, тоже не ыходило.. хз.. что-то с кодировкой самого файла ...

**Comment by awanport** [comment]
делал.  все по вашему методу он был отписан выше не получается! скиньте если не сложно свои файлы на vvk8@ya.ru

**Comment by Dsqwared** [comment]
скинул

**Comment by awanport** [comment]
Спасибо вам огромное! получилось.

**Comment by Dsqwared** [comment]
что ж было?

**Comment by awanport** [comment]
честно сам не знаю! закинул ваш файл и ОК.

**Comment by Dsqwared** [comment]
я ж говорю, мистика какая-то

**Comment by Forsik** [comment]
Ребята скиньте и мне пожалуйста рабочую версию. А то тоже не могу подключить класс

**Comment by sergejfreelancer** [comment]
Я тоже не могу подключить. Удалил шапку включая namespace и все заработало

**Comment by SergyKor** [comment]
надеялся что этот пакет облегчит работу а он только замучал ошибками. 
получить элементарно список отделений не дает.
