### ISSUE TITLE
Невозможность создания отправителя при создании ЭН

### ISSUE THREAD

**Issue by lis-dev** [lis-dev/nova-poshta-api-2#7]
Новая Почта заблокировала возможность использования контрагентов-получателей в качестве отправителей. Таким образом, отправителя теперь необходимо создавать вручную. Для большинства пользователей метод save() модели Counterparty вернет ошибку о невозможности создания им контаргента-отправителя. Поддержка Новой Почты рекомендует использовать метод cloneLoyaltyCounterpartySender() для создания контрагента с данными аккаунта в другом городе. При этом, не смотря на то, что данный метод возвращает статус true и выполняется без ошибок, вновь созданного контрагента-отправителя вы не найдете ни вызвав getCounterparties, ни в личном кабинете (здесь вы можете только увидеть, что "Контрагент создается" без получения каких-либо временных рамок). Таким образом, в данный момент нет возможности динамически создать отправителя и сразу же его использовать для создания ЭН, можно работать только с уже существующими отправителями.

**Comment by mrvova92** [comment]
сейчас совсем нет возможности создать контрагента отправителя самому? техподдержка молчит(
